name: Run JMeter Script and Send Results

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run JMeter script in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/jmeter \
          -w /jmeter \
          justb4/jmeter \
          -n -t SLAS_Pipeline_prod.jmx -l SLASresults.jtl

    - name: Send email with results
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.hostinger.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Nelfund Real User Monitoring Health - Status - Successful"
        body: "Please find the details of Application responsiveness :"
        to: deepak@thinktime.in
        from: ${{ secrets.EMAIL_USERNAME }}
        attachments: SLASresults.jtl
