name: Run JMeter Script and Send Results

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set run details
      run: |
        run_number=$(($GITHUB_RUN_NUMBER - 1)) # Subtract 1 as GITHUB_RUN_NUMBER starts from 1
        run_date=$(date +'%Y-%m-%d')
        run_time=$(TZ=Africa/Lagos date +'%I:%M %p, %Z') # Get Nigerian time
        echo "run_number=$run_number" >> $GITHUB_ENV
        echo "run_date=$run_date" >> $GITHUB_ENV
        echo "run_time=$run_time" >> $GITHUB_ENV
      
    - name: Run JMeter script in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/jmeter \
          -w /jmeter \
          justb4/jmeter \
          -n -t SLAS_Pipeline_prod.jmx -l SLASresults.jtl

    - name: Parse JTL file and prepare email content
      id: parse-results
      run: |
        parsed_results="<table style='border-collapse: collapse; width: 100%;'><tr><th style='border: 1px solid black; padding: 8px;'>PageName</th><th style='border: 1px solid black; padding: 8px;'>Response Time</th><th style='border: 1px solid black; padding: 8px;'>Status</th></tr>"
        overall_status="Successful"
        failed_labels=""
        while IFS=, read -r timeStamp elapsed label responseCode responseMessage threadName dataType success failureMessage bytes sentBytes grpThreads allThreads URL Latency IdleTime Connect; do
          if [ "$label" != "label" ]; then
            if [ $elapsed -le 5000 ]; then
              result="Pass"
            else
              result="Fail"
              overall_status="Failure"
              failed_labels="$failed_labels$label, "
            fi
            response_time=$(bc <<< "scale=2; $elapsed / 1000")
            parsed_results="$parsed_results<tr><td style='border: 1px solid black; padding: 8px;'>$label</td><td style='border: 1px solid black; padding: 8px;'>${response_time} sec</td><td style='border: 1px solid black; padding: 8px;'>$result</td></tr>"
          fi
        done < SLASresults.jtl
        # Remove trailing comma from failed_labels
        failed_labels="${failed_labels%,*}"
        parsed_results="$parsed_results</table>"

        if [ "$overall_status" = "Successful" ]; then
          summary="All transactions met the response time SLA of 5 seconds, indicating optimal performance."
        else
          summary="Please note that the following transactions failed to meet the performance criteria with a response time of 5 seconds: $failed_labels. Immediate action is required to address the performance issues identified."
        fi

        echo "parsed_results<<EOF" >> $GITHUB_ENV
        echo "$parsed_results" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "overall_status=$overall_status" >> $GITHUB_ENV
        echo "failed_labels=$failed_labels" >> $GITHUB_ENV
        echo "summary=$summary" >> $GITHUB_ENV

    - name: Send email with parsed results
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.hostinger.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Nelfund Real User Monitoring Health - #${{ env.run_number }} - ${{ env.run_date }} & ${{ env.run_time }} - Health Status - ${{ env.overall_status }}!"
        html_body: |
          <html>
          <body style="font-family: Calibri, sans-serif;">
            <p>Please find the details of Application responsiveness:</p>
            <p>${{ env.parsed_results }}</p>
            <p></p> <!-- This adds space between the parsed results and build information -->
            <p><b>Build Information:</b></p>
            <p>Build Health Status: ${{ env.overall_status }}!<br>
            Build Date and Time: ${{ env.run_date }} & ${{ env.run_time }}</p>
            
            <p><b>Summary:</b></p>
            <p>${{ env.summary }}</p>

            <p>Thanks,<br>
            QA Team.</p>

            <p>Note: This is an auto-generated email. Do not reply</p>
          </body>
          </html>
        to: deepak@thinktime.in
        from: ${{ secrets.EMAIL_USERNAME }}
        priority: normal
