name: Run JMeter Script and Send Results

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run JMeter script in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/jmeter \
          -w /jmeter \
          justb4/jmeter \
          -n -t SLAS_Pipeline_prod.jmx -l SLASresults.jtl

    - name: Parse JTL file and prepare email content
      id: parse-results
      run: |
        parsed_results="PageName\tResponse Time\tStatus\n"
        while IFS=, read -r timeStamp elapsed label responseCode responseMessage threadName dataType success failureMessage bytes sentBytes grpThreads allThreads URL Latency IdleTime Connect; do
          if [ "$label" != "label" ]; then
            if [ $elapsed -le 5000 ]; then
              result="Pass"
            else
              result="Fail"
            fi
            response_time=$(bc <<< "scale=2; $elapsed / 1000")
            parsed_results="$parsed_results$label\t$response_time sec\t$result\n"
          fi
        done < SLASresults.jtl
        echo "::set-output name=parsed_results::$parsed_results"

    - name: Send email with parsed results
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.hostinger.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Nelfund Real User Monitoring Health - Status - Successful"
        body: |
          Please find the details of Application responsiveness:

          ${{steps.parse-results.outputs.parsed_results}}
        to: deepak@thinktime.in
        from: ${{ secrets.EMAIL_USERNAME }}
