name: Run JMeter Script and Send Results

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run JMeter script in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/jmeter \
          -w /jmeter \
          justb4/jmeter \
          -n -t SLAS_Pipeline_prod.jmx -l SLASresults.jtl

    - name: Generate Report
      id: generate-report
      run: |
        jtl_content=$(cat SLASresults.jtl)

        parse_jtl_file() {
            IFS=$'\n' read -d '' -r -a lines <<< "$1"
            results=()
            for line in "${lines[@]}"; do
                IFS=',' read -r -a parts <<< "$line"
                label="${parts[2]}"
                elapsed=$(echo "scale=2; ${parts[1]}/1000" | bc)
                status="Pass"
                if (( $(echo "$elapsed > 5.0" | bc -l) )); then
                    status="Fail"
                fi
                results+=("<tr><td>$label</td><td>$elapsed sec</td><td>$status</td></tr>")
            done
            printf "%s\n" "${results[@]}"
        }

        results=$(parse_jtl_file "$jtl_content")

        table="<table border='1'><tr><th>PageName</th><th>Response Time</th><th>Status</th></tr>${results[@]}</table>"

        echo "::set-output name=table::$table"

    - name: Send email with results
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.hostinger.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Nelfund Real User Monitoring Health"
        body: |
          <p>Please find the details of Application responsiveness :</p>
          ${{ steps.generate-report.outputs.table }}
          <p><b>Build Information:</b></p>
          <p>Build Health Status: Successful!</p>
          <p>Build Date and Time: $(date +"%Y-%m-%d & %I:%M %p, %Z")</p>
          <p><b>Summary:</b></p>
          <p>All transactions met the response time SLA of 5 seconds, indicating optimal performance.</p>
          <p>Thanks,<br>QA Team.</p>
          <p>Note: This is an auto-generated email. Do not reply.</p>
        to: deepak@thinktime.in
        from: ${{ secrets.EMAIL_USERNAME }}
        attachments: SLASresults.jtl
